# Generated by Django 5.0.1 on 2024-01-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('monthly_salary', models.IntegerField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('approved_limit', models.IntegerField(blank=True, null=True)),
                ('current_debt', models.IntegerField(blank=True, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('tenure', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('monthly_payment', models.FloatField(blank=True, null=True)),
                ('paid_on_time', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.customer')),
            ],
        ),
    ]
